notifications:
  slack:
    secure: "unmQxcNFi3pCDI6cwkGQci/3CELO3eqCh9fvNXtlH1OtqEM5T4oXA9gKXscul9ElmbdiFHkUqiznXjRDmfDKK1ZSHLas3i9WuzyCFJXhJ5sWWg+CZ0x9S2nnqImE+bHvNn2jMTvxYgVTR7X9OoeK66xaWviI6VYI+VgIpydlvGBlfy1WQL81ClelDmx1bazPUlV2e0UExMB4LyyN9slnzQiMJzJrNv0T14cWJCn4dxSc7pZ9SKNL5XfZQbyQrz1FAot8fzjMeh91Yv/DsQSuPYvvwAHbUUkS4GLKzy963L3TXDHRxMzZRrlVhg8QlFR0NO7fjtmOriTpER13diypfHL8dHoRAhguF473lqsIfNJBs7/2E3Lq56ibfvas8TAcdMsV6FpFjyij0cT6NwbJg8zIhBN0jc5v+S0u0biF4b7T5ZxH3bazD4p+6ENh1N3wcVZd7oDs6tQmuhGpwF0MEPd4j6e5oDiJPMTZQDv0EOxCPoVDYXtYQIpjBe9AdELObFe50ZwSedpdg7BLt7JvI3qp3SQcXRC99Ye8ocObpzuDsKIGsSGgcxkNOe+67oxR941ol7X4iBIRXWDPpzVEHMD9+Y+5DDpSmiDHqpKyuRo415MfnR9TmHcB9m91/OFKJrJN5EjSsMQeyGVEoxiXaxKPBQpVt7u0KHsMiuHr9b0="
  email: false
env:
  secure: "nnoH8+iHQN7WvVFgb4B0YShUwkUiO0SFVkygVBFM3jdyVuqKCeTLy6wbKeAJS1koWE1Ivc3azm6pmjTCj3nymumUNDzeOtR6MvaUW8svwXsjjGsICvyMYUV/Py+xMowqFcB2arNT3JCXIDO7POKXlflDsTFJWa94SeLqla7DrrQp8W41abMoJCXKiHpsmG8NMkDcbEPZiHd+q8lN8JIKF0iz1mreRuUUBJa9QQnb7tL9WcuPhEzpIhUZfenbceXVo9XPEV2nm+o7bZu904dO6bUVRNUp2XdzftJLmbFiZq9xa+MjAqfWuPFUADQSoeETisZ3mX0BHEWd1u1WaQEDZLWxrz94C+gsfmkpG26RMT9sg4euozBhlJIt539zFJFJGD+x6/cmQr6naaRAZ6Y6Ew7k4EvtN2T0GvgHF7grR6ikgEweKPfcMRpBASBLIwIAk9R9YSmSPeG6OSlXX8UooyPSSb1zlW7GJAui9vGyrxll2v4x20gveJG3Q7eiCwjtFgFSLjDiZCDJl68HG7EwHDQbus3/9PRGVR18eyRmd4v5DdzasTI1E/5GS6qlCD3Ly2KsueDct6n1JGRZFa58D0cJXqcw1FkTuQuW7W63u2edlkfEsuanZj0bXtMV/fVydS4Ns9DW27as4PA7A7VDnaO9f4ZSazZ9w9W2blDL5NI="
dist: trusty
language: node_js
node_js:
  - '4'
cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/.cache"
addons:
  firefox: 49.0
before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
install:
  - npm install
  - bower install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: "P3/kURjVteXyW77nzfFYSgaYp1QtoBPQw4DoVOdwb86GGmPB/Z40o4pXsIYFmBAks9Wh8aaGHEzF6M6pyRXazSy9gtfj41tXHjvF/iqY2yLKa+Nyhy07jSlCaYRNgggQdR8WEIYNmFl1i0WYbI+JfvUhmFDw1/yew67p9AaoifyrymE6/gemL21BjqH4hU6zdA90Ub72/FE1Y0ai8CqYmPubLmeSUsmYMlMrJG+/CuBeW1LjnzoJdZHexp1m5Jw78+pr+79e/4x9xOscZB4mfshbD202gvAJiKoc27gkCbHslUIzucbiydD/+b8hHh2xx8S7byYZ4bKpzFZKx05CpCnMA7DmSfG80ncAxuDXhrWKVprfVYxsPPlHPSVx64QrghoiB3K3mxkOcBuOq8/krkmdiKs+KWfjxOBE+hZJ5m+I3Ps7F9+ubf3bwehLTJ2BLRtdEt+3c+1B9sI/m22rotKuvzsNcocJDJQoqT1bI2sPlAfqty4gYih1ZMTjjuqjce8wJ3LYYo2Jl2eJ37/bF8obuShaHs/IZbpku81h+6HkU6WyLv/WOQqvLSx7LECXNvpRhQNYiNlwqFiXhVVuKgXAuS3vJ8jSN+eA+ZcHP1yzkOzktmzUv3e+au17LSm+7XTdP8UHgD9fxTuTr5sYcuFBNRghbehY0EgeM8mA1cc="
  app: the-apothecary-shoppe-portal-w
